#!/usr/bin/env bash
set -e

# =============================================================================
# codeserver-ai startup script
#
# IMPORTANT ORDERING: the Node backend must bind to $PORT and respond on
# /api/health as fast as possible, no matter what code-server (or the
# codespace-wiring below) is doing — Render's health check hits the backend's
# port, and if nothing binds there quickly, Render marks the whole deploy
# "unhealthy" / 502s forever. So:
#   1. Kick off codespace resolution + code-server launch together in ONE
#      background subshell (codespace wiring happens BEFORE code-server
#      starts, so code-server opens the right folder from its very first
#      load instead of needing a reload after a live mount lands).
#   2. Start the Node backend RIGHT AWAY in the foreground (main process) —
#      it passes Render's health check immediately, independent of how long
#      codespace resolution / code-server boot takes.
#   3. Until code-server finishes booting, the backend's reverse-proxy error
#      handler (in server.js) shows a friendly "still starting…" page.
# =============================================================================

# Raise the file-descriptor limit. VS Code's file watcher (fs.watch) opens
# one watch handle per directory it tracks, and the default container limit
# (often 1024 or lower on Render) gets exhausted fast, which is why the logs
# were full of "EMFILE: too many open files" warnings. Best-effort — some
# sandboxes cap how high this can go, hence `|| true`.
ulimit -n 65536 2>/dev/null || ulimit -n 8192 2>/dev/null || true
echo "[start.sh] File descriptor limit: $(ulimit -n)"

WORKSPACE_FOLDER="/home/coder/project"
mkdir -p "$WORKSPACE_FOLDER"

(
  # ===========================================================================
  # STEP 1 — Wire the editor itself (terminal + filesystem) to the live
  # GitHub Codespace. This is best-effort: any failure here just falls back
  # to the local empty folder / plain local terminal, it never aborts the
  # container (the `|| true` / conditional guards throughout are deliberate).
  # ===========================================================================
  export GH_TOKEN="${GITHUB_TOKEN:-}"

  if [ -n "${GITHUB_TOKEN:-}" ] && [ -n "${GITHUB_SANDBOX_REPO:-}" ]; then
    echo "[start.sh] Resolving GitHub Codespace for ${GITHUB_SANDBOX_REPO} (this can take up to ~90s on first boot) …"
    CS_NAME="$(node /app/backend/resolve_codespace.js || true)"

    if [ -n "$CS_NAME" ]; then
      echo "[start.sh] Codespace resolved: ${CS_NAME}"
      REPO_BASENAME="${GITHUB_SANDBOX_REPO##*/}"
      REMOTE_PATH="/workspaces/${REPO_BASENAME}"

      mkdir -p /root/.ssh && chmod 700 /root/.ssh

      # `gh codespace ssh --config` emits an OpenSSH config block (Host alias
      # + ProxyCommand that tunnels SSH over GitHub's Codespaces connection
      # service via `gh`) — this is what makes `ssh <alias>` just work below,
      # without us managing raw host/port/keys ourselves.
      gh codespace ssh --config -c "$CS_NAME" > /root/.ssh/codespace_config 2>/tmp/gh_ssh_config.log || true

      if [ -s /root/.ssh/codespace_config ]; then
        CS_HOST="$(grep -m1 '^Host ' /root/.ssh/codespace_config | awk '{print $2}')"
        {
          echo ""
          echo "# --- BEGIN managed codespace SSH config (auto-generated by start.sh) ---"
          cat /root/.ssh/codespace_config
          echo "StrictHostKeyChecking no"
          echo "UserKnownHostsFile /dev/null"
          echo "# --- END managed codespace SSH config ---"
        } >> /root/.ssh/config
        chmod 600 /root/.ssh/config
        echo "[start.sh] SSH config ready — host alias: ${CS_HOST}"

        # --- Terminal integration -------------------------------------------
        # Default integrated terminal profile SSHes straight into the live
        # codespace, so opening a terminal panel in the editor really is the
        # codespace's terminal (not this Render container's shell).
        mkdir -p /root/.local/share/code-server/User
        cat > /root/.local/share/code-server/User/settings.json <<SETTINGSEOF
{
  "terminal.integrated.defaultProfile.linux": "Codespace",
  "terminal.integrated.profiles.linux": {
    "Codespace": {
      "path": "ssh",
      "args": ["${CS_HOST}", "-t", "cd ${REMOTE_PATH} 2>/dev/null; exec bash -l"]
    },
    "bash (local render container)": { "path": "bash" }
  }
}
SETTINGSEOF
        echo "[start.sh] Integrated terminal wired to SSH into ${CS_HOST} (${REMOTE_PATH})."

        # --- Filesystem integration ------------------------------------------
        # Try a real live SSHFS mount first (requires /dev/fuse — most PaaS
        # containers, including Render, don't grant FUSE to regular
        # non-privileged containers, so this is expected to fail there, but
        # costs nothing to attempt in case the platform ever does allow it).
        SSHFS_MOUNTED=0
        if command -v sshfs >/dev/null 2>&1 && [ -e /dev/fuse ]; then
          echo "[start.sh] /dev/fuse present — attempting SSHFS mount of ${CS_HOST}:${REMOTE_PATH} onto ${WORKSPACE_FOLDER} …"
          if sshfs "${CS_HOST}:${REMOTE_PATH}" "$WORKSPACE_FOLDER" \
               -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3,StrictHostKeyChecking=no,allow_other,default_permissions \
               2>/tmp/sshfs.log; then
            echo "[start.sh] SSHFS mount succeeded — Explorer/editor now show the LIVE codespace filesystem at ${WORKSPACE_FOLDER}."
            SSHFS_MOUNTED=1
          else
            echo "[start.sh] SSHFS mount FAILED (see /tmp/sshfs.log) — falling back to rsync-based sync."
          fi
        else
          echo "[start.sh] sshfs binary or /dev/fuse not available in this container — falling back to rsync-based sync."
        fi

        # --- Fallback: periodic bidirectional rsync-over-ssh --------------
        # No FUSE means no true live mount, so instead keep the local
        # project folder (what Explorer shows) in lockstep with the
        # codespace's real files via a background loop: pull remote changes
        # in, push local changes out, every few seconds. `rsync -e ssh`
        # spawns the REAL system ssh binary, which (unlike a pure-JS SFTP
        # client) correctly honors our ~/.ssh/config's ProxyCommand — the
        # only way to actually reach a codespace, since it has no direct
        # SSH endpoint, only GitHub's relayed tunnel that `gh` manages.
        # `--update` skips overwriting a file with an older one on either
        # side, which keeps this reasonably safe for the common case of only
        # one side (user in the editor, or the AI on the codespace) editing
        # at a time. Not instant, but Explorer reflects reality within a
        # few seconds either way.
        if [ "$SSHFS_MOUNTED" -eq 0 ] && command -v rsync >/dev/null 2>&1; then
          echo "[start.sh] Starting background rsync sync loop (~5s interval) between ${WORKSPACE_FOLDER} and ${CS_HOST}:${REMOTE_PATH} …"
          # Initial pull so Explorer isn't empty on first load.
          rsync -az --update -e "ssh -F /root/.ssh/config -o StrictHostKeyChecking=no"             "${CS_HOST}:${REMOTE_PATH}/" "$WORKSPACE_FOLDER/" >/tmp/rsync.log 2>&1 || true
          (
            while true; do
              rsync -az --update -e "ssh -F /root/.ssh/config -o StrictHostKeyChecking=no"                 "${CS_HOST}:${REMOTE_PATH}/" "$WORKSPACE_FOLDER/" >>/tmp/rsync.log 2>&1
              rsync -az --update -e "ssh -F /root/.ssh/config -o StrictHostKeyChecking=no"                 --exclude='.git/'                 "$WORKSPACE_FOLDER/" "${CS_HOST}:${REMOTE_PATH}/" >>/tmp/rsync.log 2>&1
              sleep 5
            done
          ) &
          echo "[start.sh] rsync sync loop PID: $! (log: /tmp/rsync.log)"
        fi
      else
        echo "[start.sh] 'gh codespace ssh --config' produced no output (see /tmp/gh_ssh_config.log) — skipping terminal/filesystem wiring."
      fi
    else
      echo "[start.sh] Codespace resolution failed (see logs above) — editor will use the local folder and local terminal only."
    fi
  else
    echo "[start.sh] GITHUB_TOKEN or GITHUB_SANDBOX_REPO not set — skipping codespace wiring, using local folder/terminal."
  fi

  # ===========================================================================
  # STEP 2 — Launch code-server against $WORKSPACE_FOLDER (now potentially
  # the live SSHFS-mounted codespace directory from Step 1).
  # ===========================================================================
  echo "[start.sh] Launching code-server on 0.0.0.0:8080 …"

  # IMPORTANT: code-server auto-detects the platform's $PORT env var (Render
  # injects PORT=10000) and binds to THAT instead of our explicit --bind-addr
  # flag, completely ignoring --bind-addr. That caused code-server to grab
  # port 10000 for itself, so the Node backend then crashed on startup with
  # EADDRINUSE (both trying to bind :10000), crash-looping the whole
  # container. Fix: unset PORT only inside this subshell, so code-server
  # can't see it and falls back to --bind-addr 0.0.0.0:8080.
  unset PORT
  exec code-server \
    --bind-addr 0.0.0.0:8080 \
    --auth none \
    --disable-workspace-trust \
    "$WORKSPACE_FOLDER"
) > /tmp/code-server.log 2>&1 &

CODE_SERVER_PID=$!
echo "[start.sh] code-server (+ codespace wiring) PID: ${CODE_SERVER_PID} (logs: /tmp/code-server.log)"

# Small watcher, purely informational — logs when code-server becomes
# reachable (or if it dies), but never blocks the backend from starting.
(
  for i in $(seq 1 500); do
    if curl -fsS -o /dev/null "http://127.0.0.1:8080/" 2>/dev/null; then
      echo "[start.sh] code-server became reachable after ~${i}s."
      exit 0
    fi
    if ! kill -0 "${CODE_SERVER_PID}" 2>/dev/null; then
      echo "[start.sh] code-server process exited early — check /tmp/code-server.log"
      exit 1
    fi
    sleep 1
  done
  echo "[start.sh] code-server still not reachable after 500s — check /tmp/code-server.log"
) &

echo "[start.sh] Starting Node backend on :${PORT:-10000} (foreground/main process) …"

# Run the backend in the foreground (main process, PID 1's child via exec).
# Forward signals so SIGTERM/SIGINT from Render reach the backend.
exec node backend/server.js
